In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/monthly_updates.csv")
df.columns = ["month", "total_updates", "cumulative_updates"]

# Safe datetime conversion
df["month"] = pd.to_datetime(df["month"], errors="coerce")

# Remove invalid rows
df = df.dropna(subset=["month"])

# Sort chronologically
df = df.sort_values("month").reset_index(drop=True)

df.head()

C:\Users\s.chinmayee reddy\AppData\Local\Temp\ipykernel_21440\4140925944.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["month"] = pd.to_datetime(df["month"], errors="coerce")

       month  total_updates  cumulative_updates
0 2024-11-01       17163105          1333904561
1 2024-12-01       26193030          1360097591
2 2025-01-01       24819163          1384916754
3 2025-02-01       23424931          1408341685
4 2025-03-01       20637885          1428979570

In [3]:
df["rolling_avg"] = df["total_updates"].rolling(window=3).mean()

In [4]:
df["trend_deviation"] = df["total_updates"] - df["rolling_avg"]

In [5]:
df.fillna(0, inplace=True)
df.head()

       month  total_updates  cumulative_updates   rolling_avg  trend_deviation
0 2024-11-01       17163105          1333904561  0.000000e+00     0.000000e+00
1 2024-12-01       26193030          1360097591  0.000000e+00     0.000000e+00
2 2025-01-01       24819163          1384916754  2.272510e+07     2.094064e+06
3 2025-02-01       23424931          1408341685  2.481237e+07    -1.387444e+06
4 2025-03-01       20637885          1428979570  2.296066e+07    -2.322775e+06

In [6]:
df.to_csv("../data/processed/final_features.csv", index=False)